### ISSUE TITLE
information missing on project pages

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#175]
@dnoesgaard notice that we are not showing all info on the project pages.
Is this a deliberate choice @burkeker? Any specific plans for showing it in a different way, or simply an oversight?

compare
https://demo.gbif-dev.org/project/living-atlases/gbif-spain
with 
http://drupaledit.gbif.org/living-atlases/gbif-spain

**Comment by burkeker** [comment]
Done as 5fcdc4d9e00fefd76bda8c26a25a9d326d03a27c.

**Comment by MortenHofft** [comment]
This is still an issue it seems: https://github.com/gbif/portal-feedback/issues/71
could you look into it @burkeker

**Comment by MortenHofft** [comment]
Related to previous version. Not relevant any more.
